### PR TITLE
	Set babel sourcemap option to inline when debug

### PR DESCRIPTION
**Pull request by zaaack**
For debug.

### CODE REVIEW

**Comment by zaaack** [comment]
https://github.com/kmagiera/babel-watch/issues/60

**Comment by tyronedougherty** [comment]
This PR fixes my issue (#60), would strongly like a merge! It fixes the debug mode so you can use a debugger on it. Thanks @zaaack !

cc @kmagiera

**Comment by kmagiera** [comment]
@zaaack @tyronedougherty I'd prefer for that setting to be optional or maybe only enable that when debugging flags are set? I'm afraid that this may cause a perf regression on larger projects as embedding sourcemaps often have significant impact on the file size

**Comment by zaaack** [comment]
@kmagiera You are right, I'll update this as soon as possible.

**Comment by zaaack** [comment]
@kmagiera @tyronedougherty Done.

**Comment by kmagiera** [comment]
@zaaack sorry for holding this off again but I guess I wasn't clear enough the last time.

So what I meant is that we should associate the `sourceMaps` option set with babel with `debug` command line options of babel-watch. I understand that the usecase for when the sourcemaps need to be inlined is when you run the app in debug mode, no?

I don't think allowing users to change source maps to false is something we want to do. Doing that would make it impossible to get a meaningful stack trace.

Also I realised that in the "client process" code we override uncaught handler so that the sourcemaps can be fetched from the "host process". I think this would need to be adjusted for the case when sourcemaps are inlined.

**Comment by zaaack** [comment]
@kmagiera Updated. I think I get what you mean... Looks like node-source-map-support has a option to support inline source map. Hoping I didn't make mistake.

https://github.com/evanw/node-source-map-support#options

**Comment by tyronedougherty** [comment]
Why hasn't this been merged? :S

**Comment by STRML** [comment]
Closing in favor of #118

**Comment by STRML** [comment]
Released in `7.3.0`.

**Pull request closed without merging**
