### PR TITLE
Restart on module not found

### PR DESCRIPTION
**Pull request by pfhayes**

### CODE REVIEW

**Comment by pfhayes** [comment]
See https://github.com/kmagiera/babel-watch/issues/37

Sometimes when the filesystem is changing we can erroneously say a module does not exist. This is a bit of a hacky solution where we just restart the build, but this is prone to false positives, and if a module really does not exist we will restart the build forever. Happy to consider alternative solutions to this problem

**Comment by kmagiera** [comment]
Hey @pfhayes. I merged your other pull request but am a little hesitant about this one especially because of that issue with restart loop.

I'll be happy to help with finding an alternative solution but it would be great to have a consistent repro scenario for the issue. Can you by any chance reproduce this consistently?

Also I'm a little confused that you're getting 'MODULE_NOT_FOUND' from the runner, as normally it's the role of the parent process to read source file content from the FS and at the place we call `module_._compile` we already have it loaded. 

So if you're unable to reproduce this consistently but it's still happening for you quite frequently I'd be interested in seeing the whole stack trace from the `MODULE_NOT_FOUND` error as well as seeing what is the value of `source` variable when `module_._compile` throws

**Comment by pfhayes** [comment]
Thanks @kmagiera - I understand the hesitation and would also love to find a better solution.

I am able to reproduce this consistently, but on a private repository that I can't share.

`source` appears pretty innocent at the site of the error. It mostly just requires another file (the one that can't be found). Here is is:

```jsx
'use strict';

var makeApp = require('./express/app');
var app = makeApp();
app.listen(6545);
```

It appears to have already been transformed by babel. Here is the original source:
```jsx
const makeApp = require('./express/app');
const app = makeApp();
app.listen(6545);
```

`./express/app` is a file that initializes the express app, and here is the MODULE_NOT_FOUND error:
```
{ Error: Cannot find module './express/app'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/patrick/project/js/server/express/main.js:5:17)
    at Module._compile (module.js:556:32)
    at babelWatchLoader (/Users/patrick/project/node_modules/babel-watch/runner.js:51:13)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/patrick/project/node_modules/babel-watch/runner.js:68:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by STRML** [comment]
I've seen this as well. It only seems to happen when a few files change (say, running a build job or changing branches), which causes a lot of very fast restarts:

```
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
>>> RESTARTING <<<
Error: Cannot find module './util/boot/enableDebug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/proj/util/boot/index.js:2:1)
    at Module._compile (module.js:570:32)
    at babelWatchLoader (/proj/node_modules/babel-watch/runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (/proj/node_modules/babel-watch/runner.js:61:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

Possibly just adding a little debouncing to the restart would fix this?

**Comment by pfhayes** [comment]
As far as I can tell, this issue has been resolved in https://github.com/kmagiera/babel-watch/pull/44

**Pull request closed without merging**
