### PR TITLE
Fix: Add error forwarding from babel to stderr (#143)

### PR DESCRIPTION
**Pull request by IMalyugin**
Same check list :)
- [x] Verify that locally published package works
- [x] Verify that ctrl+c stops babel-watch
- [x] Verify that underlying app crash is handled properly
- [x] Verify auto restart after changing files works
- [x] Verify manual restart via "rs" works

### CODE REVIEW

**Comment by IMalyugin** [comment]
Ready for review and merge on my side

**Comment by STRML** [comment]
How does this actually work? The try/catch isn't going to cover the callback, so it's only effectively covering this line:

https://github.com/kmagiera/babel-watch/pull/144/files#diff-3ff4a3ee3a0bfeb4fbf652e6a71273903130d817040ffac875ac6540b98e5907R432

**Comment by IMalyugin** [comment]
It actually covers the handleFileLoad, that contains compile call.

I chose to catch as much as possible - so that any error thrown inside message handler gets handled. The rest is up to call stack propagation (or promise chain if there is async action going on).

Not sure if callback is covered, depends on whether babel.transformFile is synchronous (which is probably so)

**Comment by IMalyugin** [comment]
Might as well reduce the coverage to that one babel OptionManager.init call, depends on your liking really. Either we catch all errors possible or we catch errors known to exist

**Comment by IMalyugin** [comment]
@STRML Shall we get back to the matter at hand?

I can move try/catch closer to the Babel initialization and send the error over callback, if you think that's best.

Benefits:
- local issue solved with a local patch;
- async-proof implementation;

Pitfalls:
- any other error, that may occurs in message handler will be ignored;
- extra scenario added to the workflow (handling unexpected crash in the callback);

**Comment by STRML** [comment]
I'm going to merge this, but also fix the async issue I highlighted [here](https://github.com/kmagiera/babel-watch/issues/143#issuecomment-1607549016). Thanks for the contribution.

**Pull request merged**
