### PR TITLE
fix callback DeprecationWarning. closes kmagiera/babel-watch#41

### PR DESCRIPTION
**Pull request by jibingeo**

### CODE REVIEW

**Comment by louisgv** [comment]
LGTM :+1:

**Comment by gregorskii** [comment]
👍

**Comment by inetfuture** [comment]
When this can be merged and released? That warning is really annoying. Thanks. @kmagiera

**Comment by kmagiera** [comment]
I think this has been addressed in #51 already. But thanks for the PR anyways

**Pull request closed without merging**
